### PR TITLE
Add auth level support

### PR DESCRIPTION
**Pull request by maartenhurkens**
Hi,

We found another missing feature, which is step-up authentication which we use in our portal.

I've added the functionality to add auth-level to portlets and portlet clones. It is optional so should not break current functionality.

regards, Maarten

### CODE REVIEW

**Comment by jdewinne** [comment]
Maybe check the codeclimate issue and or fix it, or explain why it is acceptable?

**Comment by maartenhurkens** [comment]
In my perspective the extra if statement wasn't really a big issue, but extracting the generation of tags into another method was an easy change, so fixed it.

**Comment by jdewinne** [comment]
@ravan Can you review and merge if possible?

**Comment by maartenhurkens** [comment]
Any updated on the review / merge of my code?

**Comment by maartenhurkens** [comment]
@ravan Thanks for merging :) Could you make a release as well?

**Pull request merged**
